import type { Metadata } from "next";
import { Caveat, Lora, DM_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight:["400","500","600","700"],
  style:["normal","italic"],
});

const dm_sans = DM_Sans({
  variable: "--font-dmsans",
  subsets: ["latin"],
  weight:["400","500","600","700","800","900"],
  style:["normal","italic"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight:["400","500","600","700"],
  style:["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${dm_sans.variable} ${caveat.variable} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
